#!/bin/bash
. /etc/environment
echo "Searching $1 for mkv files"
find $1 -name '*.mkv' -print0 | 
    while IFS= read -r -d $'\0' line; do 
        echo "Validating $line"
        filename=$(basename "$fullfile")
        /usr/local/bin/mkvalidator --quiet "$line" > "$2/${filename}.log"
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          rm "$2/${filename}.log"
        fi
    done
