#!/bin/bash
. /etc/environment
echo "Searching $1 for mkv files"
find $1 -name '*.mkv' -print0 | 
    while IFS= read -r -d $'\0' line; do 
        echo "Validating $line"
        dirname=$(dirname "$line")
        mkdir -p "$2/${dirname}"
        /usr/local/bin/mkvalidator --quiet "$line" > "$2/${line}.log" 2>&1
        STATUS=$?
        if [ $STATUS -eq 0 ]; then
          rm "$2/${line}.log"
        fi
    done
find $2 -type d -empty -delete